### ISSUE TITLE
java.lang.RuntimeException: An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by Lelight-Iot** [TuyaInc/tuyasmart_panel_android_sdk#5]
基于sdk开发接入情景业务包后，添加场景/编辑场景，选择任务-执行某个场景-执行场景/触发自动化都会闪退
然后去试了Demo 一样是会触发闪退的，无论是demo还是我这边app一样的错误
````
java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.tuya.smart.litho.mist.api.Config$ResProvider com.tuya.smart.litho.mist.api.Config.getResProvider()' on a null object reference
        at com.tuya.smart.litho.mist.core.TemplateDownloader.downloadTemplatesStatus(TemplateDownloader.java:53)
        at com.tuya.smart.litho.mist.core.TemplateSystem.syncDownloadTemplates(TemplateSystem.java:276)
        at com.tuya.smart.litho.mist.api.MistCore.downloadTemplate(MistCore.java:109)
        at com.tuya.smart.mist.litho.base.TuyaMistLithoActivity$2.doInBackground(TuyaMistLithoActivity.java:134)
        at com.tuya.smart.mist.litho.base.TuyaMistLithoActivity$2.doInBackground(TuyaMistLithoActivity.java:127)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
````

**Comment by Thewhitelight** [comment]
好的，谢谢反馈。我们会尽快修复。

**Comment by nielev** [comment]
是否引用了    implementation 'com.tuya.android:mist-litho:1.3.30' 相关依赖

**Comment by Lelight-Iot** [comment]
> 是否引用了 implementation 'com.tuya.android:mist-litho:1.3.30' 相关依赖

目前我这边的项目接入了，设备控制，情景业务，消息中心，所以自然而然有相关依赖的

````
        //...
        implementation 'com.tuya.android:mist-litho:1.3.30'
        implementation 'com.tuya.android:mist-litho-fresco:1.3.30'
        implementation 'com.tuya.android:mist-litho-sections-widget:1.3.30'
        implementation 'com.tuya.android:mist-litho-widget:1.3.30'
        implementation 'com.tuya.android:mist-litho-sections-core:1.3.30'
        implementation 'com.tuya.android:mist-litho-annotation:1.0.0'
        implementation 'com.tuya.android:mist-litho-core:1.3.30'
        // ...
````

**Comment by nielev** [comment]
https://github.com/TuyaInc/tuyasmart_mall_android_sdk  再确认一下，跑的是否是这个demo？我这边试了demo并不会崩溃

**Comment by Lelight-Iot** [comment]
> https://github.com/TuyaInc/tuyasmart_mall_android_sdk 再确认一下，跑的是否是这个demo？我这边试了demo并不会崩溃

跑的是这个 https://github.com/TuyaInc/tuyasmart_panel_android_sdk

**Comment by nielev** [comment]
https://github.com/TuyaInc/tuyasmart_mall_android_sdk   情景的demo需要参考这个库里面的使用

**Comment by nielev** [comment]
SoLoader.init(this, false);
DemoConfig config = new DemoConfig();
config.create();
MistCore.getInstance().init(config, this);有一些相关的初始化操作

**Comment by Lelight-Iot** [comment]
> SoLoader.init(this, false);
> DemoConfig config = new DemoConfig();
> config.create();
> MistCore.getInstance().init(config, this);有一些相关的初始化操作

好的，我去参考下先

**Comment by Lelight-Iot** [comment]
@nielev 感谢，添加初始化后正常了，建议这部分可以写进文档[场景业务包](https://tuyainc.github.io/tuyasmart_bizbundle_android_doc/zh-hans/pages/scene.html)中
````
SoLoader.init(this, false);
DemoConfig config = new DemoConfig();
config.create();
MistCore.getInstance().init(config, this);
````
